name: CI with Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Start backend server
        run: |
          cd backend
          nohup npm start &

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Download Keploy CLI
        run: |
          curl -L https://github.com/keploy/keploy/releases/download/v0.7.8/keploy-linux-amd64 -o keploy
          file keploy  # Should output: ELF 64-bit LSB executable
          head -10 keploy  # Print first 10 lines for debugging
          chmod +x keploy
          sudo mv keploy /usr/local/bin/

      - name: Run Keploy tests
        run: |
          cd backend
          keploy test --proxy-port 8080 --app-port 5000

      - name: Upload Keploy reports
        uses: actions/upload-artifact@v4
        with:
          name: keploy-reports
          path: backend/keploy/reports
